
AWSTemplateFormatVersion: '2010-09-09'
Description: 'static website on s3'

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'sb-s3staticwebsite'
      WebsiteConfiguration: 
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
